### ISSUE TITLE
Discussion regarding the lsp

### ISSUE THREAD

**Issue by VarLad** [lite-xl/lite-xl-lsp#1]
It's a common problem in almost every other text editor to display the docs. Because the docs are mostly md, and editors are mostly not made in Electron

A good solution I can think of is to not display the docs with autocomplete/suggestions. Instead, make a separate docs pane, where user can search keywords. The docs pane can also display the docs of the word the pointer is pointing to, in the editor. 
As for the docs pane, using something like https://github.com/Orange-OpenSource/pandoc-terminal-writer to render the md and display the docs is an idea. Another idea can be to write (something like) https://github.com/ttscoff/mdless in Lua
Either way, I think this should be the future for lsp support in lite-xl, which is worth looking into after the lsp implementation is complete

**Comment by jgmdev** [comment]
The doc pane sounds like a good option to have (maybe display it at the bottom of the editor view), but I would still prefer to have rapid access to docs on the selected autocomplete item side by side without affecting the whole document view.

> As for the docs pane, using something like https://github.com/Orange-OpenSource/pandoc-terminal-writer to render the md

Implementing a markdown renderer in lite should be possible and maybe not too difficult and it could be used on the description tooltip (or documentation pane if implemented)

> Another idea can be to write (something like) https://github.com/ttscoff/mdless in Lua

That would be the quickest solution, to convert the markdown to plaintext, all we would need is a strip_markdown(text) function until the a proper markdown renderer is written.

**Comment by VarLad** [comment]
> maybe display it at the bottom of the editor view

Yeah, many editors employ this and it works
Also, we can give an option to switch as well. My main concern being, I've seen the docs consume the entire program making it really annoying. With a pane at the bottom, we can have a scroll bar as well

**Comment by jgmdev** [comment]
> I've seen the docs consume the entire program space making it really annoying.

True, really bad on long documentation comments, perhaps also implement a scrollable tooltip, but now that you mention this the pane makes more sense and if done using the docview api may be easier to do, maybe also add a button to tooltip that says "view more" and opens the pane.

**Comment by jgmdev** [comment]
For the moment I implemented a basic markdown to plain text function and this is the result:

Before:
![2021-06-25_02:15:57](https://user-images.githubusercontent.com/1702572/123378885-50d7eb00-d55b-11eb-9a83-9c10a2aae30b.png)

After:
![2021-06-25_02:12:44](https://user-images.githubusercontent.com/1702572/123378719-19693e80-d55b-11eb-9fb5-f88ca11a4b58.png)

So until a proper markdown renderer is implemented this will do.

**Comment by jgmdev** [comment]
Leaving this here for reference https://github.com/jgm/lunamark

**Comment by VarLad** [comment]
Any way we can get highlighting here?

**Comment by jgmdev** [comment]
> Any way we can get code highlighting here? Stuff like bold and italics

Yeah, it is possible, but first we would need for lite to support that and there is discussion about implementing [support for italic and bold fonts](https://github.com/lite-xl/lite-xl/discussions/280) using the agg library.

With current lite-xl functionality one could implement a syntax highlighter every time that code sections are found as change the color and size of text depending on the kind of markdown element it is, but that requires using a proper markdown parser like the one shared above and a description popup with better encapsulated functionality as maybe what described on lite-xl [overlay system](https://github.com/lite-xl/lite-xl/discussions/294)

For the moment I will focus on the more easy things like: 
* Accents active parameter and signature
* Be able to search workspace symbols 'workspace/symbol'
* Add symbol renaming support 'textDocument/rename'
* etc...

**Comment by redtide** [comment]
FWIW I'm currently using qtcreator, which uses both docs in suggestions and has a documentation pane.
To me the "brief" documentation in suggestions is enough, usually I read the documentation in a separate context (local or website documentation) only when needed.

**Comment by VarLad** [comment]
@redtide 
The documentation pane would help in not opening a browser
Also, we can _search_ docs with a pane _without suggestions_

Again, I think, a pane should be implemented, with an option to switch between 
docs in suggestions and docs in a pane

**Comment by VarLad** [comment]
@jgmdev 
If possible, can you implement the pane for now?
We can work on pretty printing of markdown later

**Comment by redtide** [comment]
I didn't mean to exclude the doc pane, but having also the brief information of a function in suggestions, so not forcing people to open a pane.

**Comment by VarLad** [comment]
The pane must have a separate search bar
And hovering upon the suggestions from autocomplete should display docs in the pane as well

**Comment by VarLad** [comment]
Also, @redtide @jgmdev 
Anyway we can get highlighting from liteXL into the docs?

**Comment by redtide** [comment]
I'm not working on this, just an user like you.

**Comment by jgmdev** [comment]
Mouse hover is implemented and just pushed a change to allow opening a symbol hover information on a separate pane when pressing `alt+shift+a` or by executing `lsp:show-symbol-info-in-tab` or right clicking and selection it from context menu:

![lsp-help-tab](https://user-images.githubusercontent.com/1702572/197699513-9d17dd02-93e4-499a-90fb-3696d4f0c1fa.png)

Since it is just a read only docview it should allow searching, scrolling, etc...
