### ISSUE TITLE
No feedback when definition doesn't exist.

### ISSUE THREAD

**Issue by adamharrison** [lite-xl/lite-xl-lsp#102]
If you right click (or `alt+d`), on something where lsp can't find the definition, instead of getting any kind of feedback, lsp's just silent. At the very least for the right click, we should probably just flash a quick "no definition found" message.

**Comment by Guldoman** [comment]
How's 5cf12097dfa31f4a17401f43908d8a753bc1501f?

**Comment by adamharrison** [comment]
Fixed!
