### ISSUE TITLE
Rendering issues for inline diagnostics

### ISSUE THREAD

**Issue by aCursedComrade** [lite-xl/lite-xl-lsp#114]
New user here trying out lite-xl and the plugins it has. I ran into this issue that is very much similar to what #48 describes. I have tried `rust-analyzer` and `pyright` setups on my end, diagnostics do get reported correctly and viewable from status bar. Running `Lsp: Toggle Diagnostics` twice (first it disables and then enables again) renders them in the document but continues to either stay statically or disappears until I run the command twice again. I'm not seeing any errors in the logs as well.

![lite-xl-lsp_missing_inline_diagnostics](https://github.com/lite-xl/lite-xl-lsp/assets/71869007/c4c63526-a3f3-45bb-b385-77f2ef0943ba)

![lite-xl-lsp_diagnostics_arent_updated](https://github.com/lite-xl/lite-xl-lsp/assets/71869007/6336666b-3990-4b89-b7ab-803eb4726dcd)

All plugins were installed through `lpm`.

OS: Windows 10
Lite-xl version: 2.1.3
user `init.lua` and plugin hierarchy:

![lite-xl_config](https://github.com/lite-xl/lite-xl-lsp/assets/71869007/1dc80bb1-22fb-43ba-b9a4-2a5fa44ac275)

**Comment by Guldoman** [comment]
Seems to work here with `pyright` installed via the plugin `lsp_python`:

[Video del 2024-03-27 16-37-33.webm](https://github.com/lite-xl/lite-xl-lsp/assets/2798487/136bafae-3eff-4f09-8b78-0c0344ee3eb8)

Am I missing something about this issue?

Could you test with `lsp_python` too? Maybe even in an lpm bottle (`lpm run --ephemeral lsp_python`).

**Comment by aCursedComrade** [comment]
I tried `lsp_rust` and `lsp_python` in the system install before reporting here too, but it turned out be same case.

Bottles are affected as well on my end apparently: `lpm run --ephemeral lsp_python`

https://github.com/lite-xl/lite-xl-lsp/assets/71869007/47ab71ae-b34e-475f-a3ea-bf9470979bf1

PS: dont worry about the unresolved dependencies in the video, it supposed to be in a poetry managed env but it is not setup on this box.

**Comment by aCursedComrade** [comment]
Apologies for not giving any updates but I'm gonna close this issue here as I was simply trying out lite-xl out of curiosity. Could've helped more if I was more comfortable with Lua :(

**Comment by aCursedComrade** [comment]
Thank you for reaching out back to me again! I can confirm it does work flawlessly now on Windows. I'll re-close this issue as completed then. Thanks again for your time.

**Comment by Guldoman** [comment]
Thank @Callmore for finding the root cause!
