### ISSUE TITLE
clangd cannot find my compile_commands.json

### ISSUE THREAD

**Issue by paulross80** [lite-xl/lite-xl-lsp#133]
Hello. I'm trying to use lite-xl editor (latest version 2.1.5, installed using fedora dnf) with the IDE plugin, that includes this lsp plugin. I'm using [xmake](https://github.com/xmake-io/xmake) as my build tool. I made a C++23 project with modules just to test some things. I ask xmake to generate the `compile_commands.json` file, like this:

`xmake project -k compile_commands`

It works. But when I open Lite XL, some clangd errors appear, like it doesn't understand my code. I have also created a .clangd file in the project root with this content:

```
CompileFlags:
  CompilationDatabase: /home/paul/Programming/xmake/test1/
  #CompilationDatabase: .
```

I restart lite xl but the same problem persists. I have noticed that QtCreator uses this parameter for clangd: `--compile-commands-dir=`, so I edited the config.lua from this plugin to add that parameter:

```
command = { "clangd", "--background-index --compile-commands-dir=build" }
verbose = true
```
[config.zip](https://github.com/user-attachments/files/16228607/config.zip)

But since I have edited this config file, every time I open litexl, it says "[LSP]: clangd was shutdown, revise your configuration"
How can I fix this?

**Comment by Guldoman** [comment]
In theory clangd automatically finds the `compile_commands.json` file in the directory/parent directory of the source files, but I don't know much about how the search works, so I can't help you much there.

> `command = { "clangd", "--background-index --compile-commands-dir=build" }`

You need to split the parameters like this:

`command = { "clangd", "--background-index", "--compile-commands-dir=build" }`

Also, please don't edit `config.lua` directly, but use your user module:
```lua
local lspconfig = require "plugins.lsp.config"
lspconfig.clangd.setup({
  command = { "clangd", "--background-index", "--compile-commands-dir=build" },
  verbose = true
})
```

**Comment by paulross80** [comment]
I'll try splitting the parameters
User module. Can you please tell me what file is that?

**Comment by Guldoman** [comment]
> User module. Can you please tell me what file is that?

Click on the gear icon in the bottom left.
If it opens a file, that's the user module. If it opens the settings GUI, in "Core", expand "General", click on "User Module".

**Comment by paulross80** [comment]
> If it opens a file, that's the user module

Found it, thanks. I've pasted your code in that file, saved and restarted litexl. No errors
It still doesn't understand what `-fmodules-ts` and importing modules are
The directory specified here: `"--compile-commands-dir=build"` should be relative to the project root, right?

**Comment by paulross80** [comment]
Today I've tried pasting the code in the project module, using `core:open-project-module` command

```
local lspconfig = require "plugins.lsp.config"

lspconfig.clangd.setup({
  command = { "clangd", "--background-index", "--compile-commands-dir=~/Programming/xmake/test1" },
  verbose = false
})
```

After saving the file, restarted with `core:restart`
Even using the full path to the compile commands file, still doesn't work as expected. What else can I try to fix it?

**Comment by Guldoman** [comment]
What happens if you run the LSP server manually? Does it warn about a bad config?
For example try with `clangd --log=verbose --check=/path/to/a/source/file`.

**Comment by paulross80** [comment]
It works. The problem was that my project uses C++20 modules. Clang does support them, but clangd doesn't. Thanks for your help!

**Comment by Guldoman** [comment]
Glad that you found the problem!
