### ISSUE TITLE
Exists a way to get ir working with pyright?

### ISSUE THREAD

**Issue by erickod** [lite-xl/lite-xl-lsp#29]
Hi guys!
I'm trying do get it working with pyright to get typing hints. The settings I made are below:

```
lspconfig.pyright = add_lsp {
  name = "pyright",
  language = "python",
  file_patterns = { "%.py$" },
  command = { 'pyright-langserver', '--stdio' },
  verbose = true,
}
```

Despite the lsp started, I can't get any data from it in the lite-xl. I need some help.

**Comment by Guldoman** [comment]
You can now try to install `lsp_python` with [lpm](https://github.com/lite-xl/lite-xl-plugin-manager), which should simplify the setup process to just installing that plugin.

Feel free to reopen if you find difficulties when using `lsp_python`.
