### ISSUE TITLE
use `plugins.widget` instead of `widget`

### ISSUE THREAD

**Issue by takase1121** [lite-xl/lite-xl-lsp#3]
Since `widget` here is technically a plugin, it'll make sense to put it in `plugins` folder and use `plugins.widget` to require it.

**Comment by jgmdev** [comment]
I haven't applied this change because I was thinking that maybe the widget library if becoming part of lite-xl could be placed on data/widget and loaded only when a plugin requires it. Also since it doesn't do anything by itself but provides functionality for others to use.
