### ISSUE TITLE
version mismatch

### ISSUE THREAD

**Issue by mhwombat** [lite-xl/lite-xl-lsp#30]
I followed the installation instructions:

```
cd ~/.config/lite-xl/
git clone https://github.com/lite-xl/lite-xl-lsp plugins/lsp
git clone https://github.com/lite-xl/lite-xl-widgets widget
git clone https://github.com/liquidev/lintplus plugins/lintplus
```

I got the following error message:

```
Some plugins are not loaded due to version mismatch.

Plugins from directory "~/.config/lite-xl":
lsp

Please download a recent version from https://github.com/franko/lite-plugins
```
But that URL redirects to `https://github.com/lite-xl/lite-plugins`, which says the repo is archived and the new repo is at `https://github.com/lite-xl/lite-xl-plugins`, which links to this repo for lsp... which is where I started!

**Comment by Guldoman** [comment]
For Lite XL version 2.0.5 you have to use the `0.1` branch. The current `master` branch is for Lite XL `master` (and future 2.1+ versions)

**Comment by mhwombat** [comment]
That fixed it. For anyone else reading this, I used this command to get the desired branch.

git clone -b 0.1 https://github.com/lite-xl/lite-xl-lsp plugins/lsp
