### ISSUE TITLE
Running LSP without having to save?

### ISSUE THREAD

**Issue by Frityet** [lite-xl/lite-xl-lsp#33]
Currently, the LSP diagnostics only runs after save, is it possible to change this?

**Comment by Guldoman** [comment]
What LSP server are you using? Different servers support different capabilities.
For example this is clangd:

https://user-images.githubusercontent.com/2798487/186540207-39c83008-a754-402d-a9c5-10d163ba1529.mp4

**Comment by Frityet** [comment]
I was using the lua-language-server

**Comment by Guldoman** [comment]
This is with lua-language-server:

https://user-images.githubusercontent.com/2798487/187041108-86a777bf-1eaa-41a5-aafb-b31e918695a8.mp4

Keep in mind that there currently is a bug which causes that delete operations don't send updates to the server, but insertions should.
