### ISSUE TITLE
lint+ and lsp does not work well with rust-analyzer

### ISSUE THREAD

**Issue by LollipopFt** [lite-xl/lite-xl-lsp#48]
when i edit a file with mistakes in rust-analyzer server, lint+ statusview warnings do not appear despite having 12 warnings from LSP Diagnostics:
![image](https://user-images.githubusercontent.com/62802897/213685090-09b6c8b9-385f-4a6a-ac46-a8ba730ff7a1.png)
i then toggle diagnostics 2 times. 1st time nothing changes (expected as diagnostics is now turned off), 2nd time diagnostics appear (diagnostics is back to being on):
![image](https://user-images.githubusercontent.com/62802897/213685464-cd078c49-7ff9-4a4e-91f9-63bc82e61d9e.png)
i then make a single change (added a _ at the front of the input function), suddenly all the diagnostics are turned off. i need to repeat the steps above (toggle diagnostics 2 times) for the diagnostics to appear again:
![image](https://user-images.githubusercontent.com/62802897/213685974-d7175216-e28a-4967-a812-8195647a1ade.png)

i have tested this with `clangd` server on `c` files and `clangd` does not seem to have this problem. could it be the way each server is set up in `config.lua`?

OS: Windows
Version: Lite XL v2.1.1

**Comment by Guldoman** [comment]
Is this still an issue?
