### ISSUE TITLE
Error creating a process: 2

### ISSUE THREAD

**Issue by kczx3** [lite-xl/lite-xl-lsp#51]
I'm getting this error after installing this plugin a several LSP servers.  It seems to happen with all LSP servers that I installed.  Is a reboot required or something?

02/01/23 11:20:12 [ERROR] C:\Users\username\.config\lite-xl/plugins\lsp\server.lua:258: Error creating a process: 2. at ...name\AppData\Local\Programs\Lite XL\data/core/init.lua:1226

stack traceback:
[C]: in function 'process.start'
C:\Users\username\.config\lite-xl/plugins\lsp\server.lua:258: in function 'plugins.lsp.server.new'
...name\AppData\Local\Programs\Lite XL\data/core\object.lua:54: in function 'plugins.lsp.symbolresults.__call'
C:\Users\username\.config\lite-xl/plugins\lsp/init.lua:683: in function 'plugins.lsp.start_server'
C:\Users\username\.config\lite-xl/plugins\lsp/init.lua:2047: in function <C:\Users\username\.config\lite-xl/plugins\lsp/init.lua:2046>
[C]: in function 'xpcall'
...name\AppData\Local\Programs\Lite XL\data/core/init.lua:1225: in function 'core.try'
(...tail calls...)

**Comment by kiprou** [comment]
Related to: https://github.com/liquidev/lintplus/issues/28

**Comment by Guldoman** [comment]
I think this was fixed by #69. Feel free to reopen if that's not the case.
