### ISSUE TITLE
How could I specify the TCP port?

### ISSUE THREAD

**Issue by iahung** [lite-xl/lite-xl-lsp#52]
For example, if the language server uses a custom TCP port, how could I specify it so Lite XL could know and use this port?

**Comment by Guldoman** [comment]
There is no support for it at the moment.
In the past I experimented with the godot language server by using `netcat`:
```lua
local lsp = require "plugins.lsp"
lsp.add_server {
  name = "godot-language-server",
  language = "gdscript",
  file_patterns = { "%.gd$", "%.tscn$" },
  command = {"netcat", "localhost", "6005"},
  verbose = false
}
```
We might add direct support for it in the future.

**Comment by iahung** [comment]
> There is no support for it at the moment. In the past I experimented with the godot language server by using `netcat`:
> 
> ```lua
> local lsp = require "plugins.lsp"
> lsp.add_server {
>   name = "godot-language-server",
>   language = "gdscript",
>   file_patterns = { "%.gd$", "%.tscn$" },
>   command = {"netcat", "localhost", "6005"},
>   verbose = false
> }
> ```
> 
> We might add direct support for it in the future.

Please consider adding direct support for it.

**Comment by iahung** [comment]
@Guldoman Does this implementation of LSP only support operating over stdin and stdout?

**Comment by Guldoman** [comment]
Yes, but you can use the `netcat` method (or an alternative available on your OS) to make it work.
