### ISSUE TITLE
LSP error: Use of undeclared identifier

### ISSUE THREAD

**Issue by Kabcorp** [lite-xl/lite-xl-lsp#63]
If I write a character like ² é à è £ ù etc.. lsp keep them as an "undeclared identifier" even if I remove the character.
Even if I save the file, the error still here, so I have to Core:Restart, then error disappears.
![lspissue](https://github.com/lite-xl/lite-xl-lsp/assets/33150965/2fb21181-e97c-473c-9b16-a1dd8a02e77f)
![lspissue3](https://github.com/lite-xl/lite-xl-lsp/assets/33150965/b75996d2-465f-4481-aa95-1cea9406fd94)

**Comment by Guldoman** [comment]
Looks like an issue with UTF-8 multi-bytes chars. Can confirm it happens with multiple LSPs.

Instead of `Core:Restart`, `Core:Reload` might be a bit faster as a temporary workaround.

**Comment by jgmdev** [comment]
A `Doc: Reload` would be enough, I gotta fix this annoying thing but I haven't paid attention on what is causing it

**Comment by Guldoman** [comment]
> A `Doc: Reload` would be enough

Ah yeah, meant that one...

The issue is likely that `add_change` should receive characters instead of bytes.
https://github.com/lite-xl/lite-xl-lsp/blob/061676efa0344c48aba18ea43688da1eaf444afb/init.lua#L2161-L2179

**Comment by Guldoman** [comment]
@Kabcorp Could you test #66? I should have fixed it also for UTF-16 characters that require 4 bytes.

**Comment by Guldoman** [comment]
What LSP server are you using?

**Comment by Guldoman** [comment]
This is with clangd and #66 applied:

[Video del 2023-07-09 18-19-59.webm](https://github.com/lite-xl/lite-xl-lsp/assets/2798487/29ebe764-0b2d-47c0-addc-608f8f569fa0)

**Comment by Kabcorp** [comment]
I use the LSP from 14 may 2023
I updated the 3 files you pulled in #66
