### ISSUE TITLE
check is always failing

### ISSUE THREAD

**Issue by SwissalpS** [lite-xl/lite-xl-lsp#64]
While debugging why lsp is not finding lua-language-server, I added a print statement here:
https://github.com/lite-xl/lite-xl-lsp/blob/061676efa0344c48aba18ea43688da1eaf444afb/util.lua#L232

these all fail as ``comand`` already has an absolute path included.
e.g. it checks for "/home/ted/.local/bin//home/ted/liteXL/user/plugins/lsp_lua/bin/lua-language-server"

There also is no directory "/home/ted/liteXL/user/plugins/lsp_lua" only ".../plugins/lsp_lua.lua" and ".../plugins/lsp/" but no "bin" in that one.  

I have lua-language-server installed in "/home/ted/lua-language-server/bin/lua-language-server" and a wrapper executable in one of my $PATH directories.  
calling ``$ lua-language-server`` from anywhere works, server starts.

Do I need to create "/home/ted/liteXL/user/plugins/lsp_lua/bin/" and put the wrapper script in there? From reading the readme, it seemed having it on $PATH was suficient.

**Comment by SwissalpS** [comment]
the readme I refered to is from the lua-language-server repo: https://github.com/LuaLS/lua-language-server/wiki/Getting-Started (so maybe offtopic in that sense, sorry) The issue remains though.

**Comment by SwissalpS** [comment]
BTW, adding this config did not help either
```lua
local lspconfig = require "plugins.lsp.config"
lspconfig.sumneko_lua.setup({
  command = {
    "/home/ted/lua-language-server/bin/lua-language-server",
    "-E",
    "/home/ted/lua-language-server/bin/main.lua"
  }
})
```

... until I disabled lsp_lua plugin. Now they seem to be communicating.

**Comment by Guldoman** [comment]
> While debugging why lsp is not finding lua-language-server, I added a print statement here:
> 
> https://github.com/lite-xl/lite-xl-lsp/blob/061676efa0344c48aba18ea43688da1eaf444afb/util.lua#L232
> 
> these all fail as `comand` already has an absolute path included. e.g. it checks for "/home/ted/.local/bin//home/ted/liteXL/user/plugins/lsp_lua/bin/lua-language-server"

It should return here

https://github.com/lite-xl/lite-xl-lsp/blob/061676efa0344c48aba18ea43688da1eaf444afb/util.lua#L202-L208

if the path is absolute and exists.

> ... until I disabled lsp_lua plugin. Now they seem to be communicating.

The `lsp_lua` plugin is to be used with `lpm`. It installs the LSP server automatically, and points the LSP plugin to it.

**Comment by SwissalpS** [comment]
> It should return here

yes, and it doesn't ever find anything because it's checking for existance of a file that can't exist as two paths are concatinated.

So unless config is setup correctly, so that this function isn't used, it will never find anything.

> The lsp_lua plugin is to be used with lpm. It installs the LSP server automatically, and points the LSP plugin to it.

OK, IC. Thanks :D

**Comment by Guldoman** [comment]
> yes, and it doesn't ever find anything because it's checking for existance of a file that can't exist as two paths are concatinated.

Where is it concatenating the paths?

**Comment by SwissalpS** [comment]
line 232: ``path_fix ... command``
``command`` already holds an absolute path at this point and ``path_fix`` is prepended to it.

(again, this happened because [lsp_lua] was installed and it overwrote the default and also the setting in user module)

**Comment by Guldoman** [comment]
> line 232: `path_fix ... command` `command` already holds an absolute path at this point and `path_fix` is prepended to it.

Before that, the check on lines 202-208 takes care of it. So if the file actually exists, it doesn't go through the "appending" part.

> (again, this happened because [lsp_lua] was installed and it overwrote the default and also the setting in user module)

I see, so there is no bug?

**Comment by SwissalpS** [comment]
not an important bug, just in some cases a useless check-loop
