### ISSUE TITLE
allow overriding PATH

### ISSUE THREAD

**Issue by CosmicToast** [lite-xl/lite-xl-lsp#84]
This should be overridable both locally and globally.
Launching Lite in "UI" mode might not get a number of environment sources (environment.d on many DE/WMs, fish_user_path, more).

This usually isn't too big an issue, since you can specify an absolute path to an LSP server...
But wouldn't it be nicer if you could have defaults in one spot (say, `local.lua`), and have all the hand-installed LSP work normally?

More importantly, some LSPs expect other binaries - for instance, gopls expects go to be in PATH, failing if it isn't.
As things are now, there's no easy way without doing some system modifications to get that running.

Ideally, lite-xl would allow `putenv` via `os.setenv`, but lua's stdlib doesn't have it for portability reasons.

I tried to add this by extending `options` and `Server` internals to pass an `env` option to `process.start`, but ran into a bug in lite-xl (I will be cross-linking shortly).

**Comment by Guldoman** [comment]
Yeah, makes sense, and
> I tried to add this by extending `options` and `Server` internals to pass an `env` option to `process.start`, but ran into a bug in lite-xl

seems the way to go.

**Comment by CosmicToast** [comment]
For the global override, https://github.com/lite-xl/lite-xl/issues/1702 should be sufficient, if it comes to be.

**Comment by Guldoman** [comment]
Could you test if #97 is enough for your use-cases?
